"""LLM prompt templates for University Challenge transcript parsing."""

from uc_transcripts.models import Transcript, VideoMetadata


SCHEMA = """
{
  "episode": {
    "series": number | null,
    "episode": number | null,
    "date": string | null,
    "teams": [string] | null
  },
  "questions": [
    {
      "question_number": number,
      "type": "starter",

      "question_mode": "text" | "picture" | "music",
      "question_text": string | null,
      "full_question_read": boolean,

      "attempts": [
        {
          "team": string | null,
          "attempted_answer": string | null,
          "outcome": "correct" | "incorrect" | "pass" | null
        }
      ],

      "correct_answer": string | null,
      "bonuses_awarded": boolean,

      "category": {
        "primary": string | null,
        "secondary": [string] | null
      }
    },
    {
      "question_number": number,
      "type": "bonus",

      "question_mode": "text" | "picture" | "music",
      "intro_text": string | null,

      "parts": [
        {
          "part": "a" | "b" | "c",
          "text": string | null,
          "attempted_answer": string | null,
          "correct_answer": string | null,
          "outcome": "correct" | "incorrect" | "not_attempted" | null
        }
      ],

      "category": {
        "primary": string | null,
        "secondary": [string] | null
      }
    }
  ]
}
"""


QBREADER_TAXONOMY = """
QBReader category taxonomy (choose exactly one primary and up to two secondary):

Literature:
- Literature; American Literature; British Literature; Classical Literature;
  European Literature; World Literature; Other Literature; Drama; Long Fiction;
  Poetry; Short Fiction; Misc Literature

History:
- History; American History; Ancient History; European History;
  World History; Other History

Science:
- Science; Biology; Chemistry; Physics; Other Science; Math; Astronomy;
  Computer Science; Earth Science; Engineering; Misc Science

Fine Arts:
- Fine Arts; Visual Fine Arts; Auditory Fine Arts; Other Fine Arts;
  Architecture; Dance; Film; Jazz; Musicals; Opera; Photography; Misc Arts

RMPSS:
- Religion; Mythology; Philosophy; Social Science; Anthropology; Economics;
  Linguistics; Psychology; Sociology; Other Social Science

Other:
- Movies; Music; Sports; Television; Video Games; Other Pop Culture;
  Geography; Current Events; Other Academic
"""


UC_PARSING_RULES = """
CORE UNIVERSITY CHALLENGE RULES

1. A starter question is a SINGLE question, even if it is interrupted multiple times.
   Do NOT split a starter into multiple questions if the host resumes reading after
   an incorrect buzz.

2. The host may read a starter in several segments due to interruptions.
   Accumulate all host-read text for a starter into ONE question_text field.

3. A starter may have MULTIPLE buzz attempts.
   For each attempt, record:
   - team
   - attempted_answer
   - outcome (correct / incorrect / pass)

4. The moderator always states the canonical correct answer.
   Extract this and store it in correct_answer for:
   - each starter
   - each bonus part
   Even if all teams answer incorrectly.

5. Bonuses occur ONLY after a correctly answered starter.
   Bonuses always consist of exactly three ordered parts (a, b, c)
   and must be grouped into a single bonus object.

6. Keep all questions in the order they appear.
   Ignore introductions, scores, and non-question chatter.
"""


QUESTION_MODE_RULES = """
QUESTION MODE

Assign question_mode as:
- "text"    : question is fully textual
- "picture" : question depends on images not present in transcript
- "music"   : question depends on music/audio not present in transcript

Use cues such as:
- "Picture starter"
- "You will see..."
- "You will hear..."
- "Music question"

Do NOT attempt to reconstruct missing images or music.
"""


def build_uc_parse_prompt(transcript: Transcript, metadata: VideoMetadata) -> str:
    """
    Build the full prompt for parsing a University Challenge episode transcript.

    Args:
        transcript: Transcript object with snippets
        metadata: Video metadata (title, date)

    Returns:
        Complete prompt string for LLM
    """
    header = f"Title: {metadata.title} | Date: {metadata.published_at}"
    text = " ".join([s.text for s in transcript.snippets])
    full_transcript = header + "\n" + text

    prompt = f"""
You are parsing a transcript of a University Challenge episode into structured JSON.

OUTPUT RULES
- Output valid JSON only.
- No explanations or commentary.
- Use null for unknown fields.
- Follow the schema exactly.

TRANSCRIPT QUALITY AND NOISE
- The transcript is auto-generated by speech recognition and may contain
  misspellings, dropped words, or garbled phrases.
- Prefer structural cues (speaker turns, order, host responses) over exact wording.
- Do NOT guess or invent missing information; use null if uncertain.

{UC_PARSING_RULES}

{QUESTION_MODE_RULES}

CATEGORY RULES
- Use the QBReader taxonomy below.
- Choose exactly one primary category.
- Choose up to two secondary categories.
- Do NOT invent categories.

QBReader taxonomy:
{QBREADER_TAXONOMY}

JSON SCHEMA:
{SCHEMA}

TRANSCRIPT:
\"\"\"
{full_transcript}
\"\"\"
"""

    return prompt.strip()
